/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/scttfrdmn/objectfs/sdks/c */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 67 "main.go"


#include "objectfs_types.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

// objectfs_client_t is an opaque token, not an address: it carries an int64 index into a Go-side
// handle table and is never dereferenced on either side. Converting between the two is done here,
// in C, rather than in Go with unsafe.Pointer(uintptr(id)).
//
// go vet reports that Go form as "possible misuse of unsafe.Pointer" and it is right to: the rule
// it enforces is that an integer must not become a pointer, because Go's garbage collector may move
// an object and will not update a value it cannot see is a reference. It has no way to express "this
// pointer is a token", and it runs outside golangci-lint, so a //nolint directive does not silence
// it — the two lines that carried one had never suppressed anything.
//
// Doing the arithmetic in C makes that structurally true instead of asserted. The value never exists
// as a Go pointer, so there is nothing for the collector to misinterpret, and the intent is stated
// by which language the cast is written in.
//
// They are typed objectfs_client_t rather than void *: cgo gives the typedef its own Go type, so a
// void * helper would return unsafe.Pointer and need a conversion at every call site — which is the
// conversion this exists to remove.
static inline objectfs_client_t objectfs_id_to_handle(int64_t id) { return (objectfs_client_t)(intptr_t)id; }
static inline int64_t objectfs_handle_to_id(objectfs_client_t h)  { return (int64_t)(intptr_t)h; }

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern objectfs_client_t objectfs_new(char* bucket, char* region, long cacheBytes);
extern void objectfs_free(objectfs_client_t handle);
extern int objectfs_get(objectfs_client_t handle, char* key, void** dataOut, size_t* lenOut);
extern int objectfs_put(objectfs_client_t handle, char* key, void* data, size_t length);
extern int objectfs_delete(objectfs_client_t handle, char* key);
extern int objectfs_head(objectfs_client_t handle, char* key, objectfs_info_t* infoOut);
extern int objectfs_list(objectfs_client_t handle, char* prefix, int limit, objectfs_list_result_t* resultOut);
extern int objectfs_mount(objectfs_client_t handle, char* mountpoint);
extern int objectfs_unmount(objectfs_client_t handle);
extern char* objectfs_last_error(objectfs_client_t handle);
extern void objectfs_free_data(void* data);
extern void objectfs_free_list(objectfs_list_result_t* result);

#ifdef __cplusplus
}
#endif
