# ObjectFS Configuration - High-Performance Streaming
# Best for: Video streaming, log processing, sequential file access

performance:
  cache_size: 4GB                         # Larger cache for streaming
  write_buffer_size: 32MB                 # Larger buffers
  max_concurrency: 200
  read_ahead_size: 128MB                  # Large read-ahead for streaming

  # Optimized for sequential streaming workloads
  read_ahead:
    enabled: true
    size: 128MB                           # Large buffer for streaming
    strategy: predictive
    sequential_min_size: 512KB            # Detect smaller sequential patterns

    # Aggressive pattern detection
    enable_pattern_detection: true
    sequential_threshold: 0.6             # More aggressive (60% confidence)
    prediction_window: 50                 # Shorter window for faster detection

    # Aggressive prefetching
    enable_prefetch: true
    max_concurrent_fetch: 8               # More parallelism for high throughput
    prefetch_ahead: 5                     # Fetch further ahead
    prefetch_bandwidth_mbs: 50            # Higher bandwidth allocation
    confidence_threshold: 0.6             # Lower threshold for more prefetching

    # ML disabled (predictive sufficient for streaming)
    enable_ml_prediction: false
    ml_model_path: ''
    learning_rate: 0.01
    pattern_depth: 1000

    # Metrics for monitoring streaming performance
    metrics_enabled: true
    statistics_interval: 15s              # Frequent monitoring
    model_update_interval: 5m
