# ObjectFS Configuration - Predictive Read-ahead
# Best for: Sequential access, batch processing, production deployments

performance:
  cache_size: 2GB
  write_buffer_size: 16MB
  max_concurrency: 150
  read_ahead_size: 64MB

  # Predictive read-ahead configuration (DEFAULT)
  read_ahead:
    enabled: true
    size: 64MB
    strategy: predictive                  # Pattern detection enabled
    sequential_min_size: 1MB

    # Pattern detection settings
    enable_pattern_detection: true
    sequential_threshold: 0.7             # 70% confidence for sequential
    prediction_window: 100                # Analyze last 100 accesses

    # Intelligent prefetching
    enable_prefetch: true
    max_concurrent_fetch: 4               # 4 parallel prefetch operations
    prefetch_ahead: 3                     # Prefetch 3 blocks ahead
    prefetch_bandwidth_mbs: 10            # Max 10 MB/s for prefetch
    confidence_threshold: 0.7             # 70% confidence to trigger

    # ML disabled (use predictive only)
    enable_ml_prediction: false
    ml_model_path: ''
    learning_rate: 0.01
    pattern_depth: 1000

    # Metrics enabled for monitoring
    metrics_enabled: true
    statistics_interval: 30s
    model_update_interval: 5m
