# ObjectFS Configuration - ML-based Read-ahead
# Best for: Complex workloads, large-scale processing, trained models available

performance:
  cache_size: 4GB                         # Larger cache for ML
  write_buffer_size: 16MB
  max_concurrency: 150
  read_ahead_size: 64MB

  # ML-based read-ahead configuration (ADVANCED)
  read_ahead:
    enabled: true
    size: 64MB
    strategy: ml                          # ML-based strategy
    sequential_min_size: 1MB

    # Pattern detection settings (feeds ML model)
    enable_pattern_detection: true
    sequential_threshold: 0.7
    prediction_window: 200                # Larger window for ML analysis

    # Intelligent prefetching
    enable_prefetch: true
    max_concurrent_fetch: 4
    prefetch_ahead: 3
    prefetch_bandwidth_mbs: 20            # Higher bandwidth for ML
    confidence_threshold: 0.75            # Higher confidence for ML predictions

    # ML prediction settings
    enable_ml_prediction: true
    ml_model_path: /var/lib/objectfs/models/access-prediction.bin
    learning_rate: 0.01                   # Adaptive learning rate
    pattern_depth: 2000                   # Deep pattern analysis

    # Metrics and monitoring
    metrics_enabled: true
    statistics_interval: 1m               # More frequent stats for ML
    model_update_interval: 10m            # Regular model updates
