package offerfile

import (
	"bytes"
	"fmt"
	"go/format"
	"slices"
	"strconv"
	"strings"

	"github.com/scttfrdmn/objectfs/internal/awsname"
)

// classConst maps a storage class to the awsname constant that names it, so the generated file
// refers to the constants rather than restating the string literals.
//
// A map rather than a name derivation, because the constant names are not mechanically related to
// the values: StorageClassIntelligent holds "INTELLIGENT_TIERING" and StorageClassGlacierIR holds
// "GLACIER_IR". Deriving them would be a second place the mapping is written down.
var classConst = map[string]string{
	awsname.StorageClassStandard:          "StorageClassStandard",
	awsname.StorageClassIntelligent:       "StorageClassIntelligent",
	awsname.StorageClassStandardIA:        "StorageClassStandardIA",
	awsname.StorageClassOneZoneIA:         "StorageClassOneZoneIA",
	awsname.StorageClassGlacierIR:         "StorageClassGlacierIR",
	awsname.StorageClassGlacier:           "StorageClassGlacier",
	awsname.StorageClassDeepArchive:       "StorageClassDeepArchive",
	awsname.StorageClassReducedRedundancy: "StorageClassReducedRedundancy",
}

// Emit renders the generated regional rate table as gofmt'd Go source.
//
// Rates are written as decimal literals with the trailing zeros trimmed, not as the strings AWS
// publishes and not via %g. AWS publishes "0.0000004000"; %g renders that as 4e-07, which is the same
// float64 and is unreadable next to the $0.004-per-10,000 it comes from. Every value in the file
// should be greppable against the AWS pricing page.
func Emit(regions []Region) ([]byte, error) {
	slices.SortFunc(regions, func(a, b Region) int { return strings.Compare(a.Code, b.Code) })

	var buf bytes.Buffer

	buf.WriteString(generatedHeader)

	fmt.Fprintf(&buf, "// regionalRates was generated from %d regions.\n", len(regions))
	buf.WriteString("var regionalRates = map[string]map[string]Rate{\n")

	for _, r := range regions {
		fmt.Fprintf(&buf, "\t%q: {\n", r.Code)

		for _, class := range awsname.StorageClasses() {
			rate, ok := r.Rates[class]
			if !ok {
				return nil, fmt.Errorf("region %s has no rate for %s; emitting the file "+
					"without it would price that class at zero", r.Code, class)
			}

			name, ok := classConst[class]
			if !ok {
				return nil, fmt.Errorf("no awsname constant recorded for storage class %q; "+
					"add it to classConst rather than emitting a string literal", class)
			}

			fmt.Fprintf(&buf, "\t\tawsname.%s: {\n", name)
			fmt.Fprintf(&buf, "\t\t\tStoragePerGBMonth: %s,\n", num(rate.StoragePerGBMonth))
			fmt.Fprintf(&buf, "\t\t\tPutRequest:        %s,\n", num(rate.PutRequest))
			fmt.Fprintf(&buf, "\t\t\tGetRequest:        %s,\n", num(rate.GetRequest))
			fmt.Fprintf(&buf, "\t\t\tListRequest:       %s,\n", num(rate.ListRequest))
			fmt.Fprintf(&buf, "\t\t\tRetrievalPerGB:    %s,\n", num(rate.RetrievalPerGB))
			fmt.Fprintf(&buf, "\t\t\tEgressPerGB:       %s,\n", num(rate.EgressPerGB))
			buf.WriteString("\t\t},\n")
		}

		buf.WriteString("\t},\n")
	}

	buf.WriteString("}\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt the generated table: %w", err)
	}

	return src, nil
}

// num formats a rate as a decimal literal.
//
// 'f' with -1 precision rather than %v or %g: both switch to exponent notation for the small
// per-request rates, and 4e-07 is not a number anyone can check against AWS's pricing page.
func num(v float64) string {
	if v == 0 {
		return "0"
	}

	return strconv.FormatFloat(v, 'f', -1, 64)
}

const generatedHeader = `// Code generated by internal/awsrates/offerfile. DO NOT EDIT.
//
// Regenerate with:
//
//	go generate ./internal/awsrates/...
//
// Source: the public AWS price list offer files, which need no credentials:
//
//	https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonS3/current/<region>/index.json
//	https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AWSDataTransfer/current/<region>/index.json
//
// The rules that turn those files into these numbers, and the case that forced each rule, are
// documented in internal/awsrates/offerfile. Read them before changing a value here by hand — every
// value that looks wrong in this file has been wrong for a reason that is written down there, and
// three of them are cases where the obvious query returns a plausible number from the wrong SKU.

package awsrates

import "github.com/scttfrdmn/objectfs/internal/awsname"

`
